### ISSUE TITLE
KerML input character encoding?

### ISSUE THREAD

**Issue by emanuelpalm** [Systems-Modeling/SysML-v2-Release#10]
Looking at Section `7.1.2 Lexical Structure` of the [Part 1 - Kernel Modeling Language (KerML)](https://github.com/Systems-Modeling/SysML-v2-Release/blob/master/doc/1-Kernel_Modeling_Language_(KerML).pdf) document, I cannot find any indications about which input encoding is assumed for source files. Is only ASCII supported, or is all of UTF-8 supported? Anything else?

I guess this would only have bearing on comments and the `UnrestrictedName` token, which is defined in terms of what characters it must not consist of. If all of UTF-8 is supported, then it would be acceptable to use non-English characters.

**Comment by seidewitz** [comment]
The pilot implementation currently does support UTF-8 encoding for characters in unrestricted names, strings and comments. Indeed, you can many examples of this in the current `SI` library (for example, the symbolic name of the Ohm unit of resistance is `SI::'Ω'`). 

How to address this in the specification is under discussion by the submission team. Since SysML v2 will ultimately be an international standard, it is important that it not be limited to ASCII, or even just the Latin character set. So, Unicode will certainly be supported, and likely UTF-8 specifically.
