### ISSUE TITLE
Role names owned by the association are never described in the abstract syntax in KerML doc

### ISSUE THREAD

**Issue by domroy** [Systems-Modeling/SysML-v2-Release#20]
Many role names are not mentioned in any place in the KerML document.

For example, typeWithEndFeature can be seen only in 'Figure 11. Types' but is not declared in the formal abstract syntax. It is used in the formal definition :

  /endOwningType : Type [0..1] {subsets typeWithEndFeature, owningType}, 

an attribute of Feature, but it was never described before or after. It will be used in the definition of other attributes too.

It is an example of a role that is owned by its association therefore no class owns them. Roles that are not attributes are not described. Maybe all associations should be described even if they describe already described attributes. Or only those roles that are not an attribute could be described.

I think there should be a way to declare them to have a complete formal abstract syntax. Somebody, may know more than me how to do that, I don't really know.

**Comment by seidewitz** [comment]
The abstract syntax metamodel does contain documentation the non-navigable, association-owned end properties shown on the diagrams. However, since we are not currently generating documentation for the associations themselves, there is no place to put the documentation for the properties they own. We may include meta-association documentation in a future draft of the spec documents, but the documentation for these "inverse" properties is generally not very interesting. For example, the description of `typeWithEndFeature` is "A Type that has an EndFeatureMembership in which the `endFeature` is a `memberFeature`."
