### ISSUE TITLE
Improve visual style

### ISSUE THREAD

**Issue by claell** [Systems-Modeling/SysML-v2-Release#30]
I suggest to improve the visual style (as example the presentation https://github.com/Systems-Modeling/SysML-v2-Release/blob/master/doc/Intro%20to%20the%20SysML%20v2%20Language-Graphical%20Notation.pdf).

The SysML v2 Logo looks a bit dated in my eyes.
![grafik](https://user-images.githubusercontent.com/6171135/126812862-325ae484-0097-45c7-a381-00144cc21b0e.png)

Also, the SysML v2 marker in the presentation looks not that modern (plus is likely used in a pretty low resolution, at least it looks blurred on my screen):
![grafik](https://user-images.githubusercontent.com/6171135/126812694-94459e48-64ae-4154-b1d9-abf77489c40e.png)

**Comment by seidewitz** [comment]
The logo is intended to reflect continuity with the SysML v1 logo. Since the SysML logo is actually a trademark of OMG, they may decide on a more professionally developed logo after v2 is formally adopted. The graphic design is not a particular priority now, and keeping the current logo provides cohesiveness for the SST effort.

**Comment by claell** [comment]
Thanks for your fast replies!
