### ISSUE TITLE
SysML: ScalarQuantityValue as subtype of VectorQuantityValue

### ISSUE THREAD

**Issue by mickbaggen** [Systems-Modeling/SysML-v2-Release#47]
In the document "OMG Systems Modeling Language" (release 2021-12), par. 9.5.2, the attributes TensorQuantityValue, VectorQuantityValue and ScalarQuantityValue are introduced. Here TensorQuantityValue is a quantity of any order (0,1,2,3,....). and VectorQuantityValue is a subtype of TensorQV of order 1. This seems correct, since order 1 is  a subtype of order _any_.

However, ScalarQuantityValue is positioned as a quantity of order 0, and a subtype of VectorQuantityValue. The former is correct, the latter does not seem correct. A quantity of order 0 is not a subtype of a quantity of order 1. Therefore, I believe that ScalarQuantityValue should be a direct subtype of TensorQuantityValue, and sit "next to" VectorQuantityValue.

The same argument would apply to TensorMeasurementReference, VectorMeasurementReference and ScalarMeasurementReference.

**Comment by hpdekoning** [comment]
[Just noticed this issue today ...]
@mickbaggen I agree you have a point here.

In my view for consistency, and also to enable transparent use of 1D coordinate transformations on scalar quantity scales (i.e. to translate for the zero offset between interval scales), the correct solution is to constrain VectorQuantityValue and VectorMeasurementReference to have `order <= 1` (instead of =1), so that ScalarQuantityValue and ScalarMeasurementReference are indeed correct subtypes of their Vector... generalizations. I will take care of this in the next release. In terms of type a scalar quantity is then a 1-vector quantity with `order == 0` and `dimensions == 1`.

Note: In KerML and SysML textual notation a collection initializer consists of a comma separated sequence of values enclosed by parentheses. A sequence of one value may be written with or without parentheses, so the following expressions are equivalent:
```
attribute :>> dimensions = 1;
attribute :>> dimensions = (1);
```

**Comment by mickbaggen** [comment]
@hpdekoning I agree your proposal corrects the correctness of subtyping. However, the more fundamental question still remains: can a Scalar (in the mathematical sense) be considered as a (subtype of) Vector ? Or the other way around: can a Vector have order = 1 or order = 0? It would seem that a scalar onlu had magnitudem bu no direction, whereas a vector always has a magnitude and (exactly) 1 direction. See e.g. https://www.toppr.com/guides/physics/difference-between-scalar-and-vector/. A tensor of order n would have a magnitude and (exactly) n directions.

**Comment by conradbock** [comment]
The reason scalars are vectors is they have a basis (compare to Real, etc, that don't, even tho in CS sometimes reals are called "scalars", they aren't mathematical scalars).  I think HP's proposal to change VectorQuantityValue and VectorMeasurementReference to have order <= 1 (instead of =1) is correct.  It fits with ISO Quantities being numbers and units, where units are analogous the basis (ie, the number is dependent on the basis).

**Comment by conradbock** [comment]
Just noticed [wikipedia](https://en.wikipedia.org/wiki/Scalar_(mathematics)) doesn't seem to agree with me.  :)   I think it confuses the number of components (scalars having one, vectors more than one) with direction, because direction obviously requires more than one component, but components still depend on the basis regardless of how many there are.  They seem to start from magnitude and direction, which are slippery terms.  Do tensors have direction? Can magnitudes be negative, or is that direction (eg, can speed be negative or should it always be positive, leaving direction to velocity vectors)? Other discussion about this on [quora](https://www.quora.com/How-does-one-distinguish-between-a-one-dimensional-vector-and-a-scalar).

Compare to [Wolfram](https://mathworld.wolfram.com/Scalar.html), which says scalars "are one component quantities", like a "short" vector.  It also says they're invariant under rotations of the coordinate system (basis), which would be consistent with that (wiki claims invariance under changes in basis, which I think is too general, since some changes in basis change the length of vectors).

**Comment by seidewitz** [comment]
This is addressed in release 2022-02 (see https://github.com/Systems-Modeling/SysML-v2-Pilot-Implementation/pull/338).
