### ISSUE TITLE
Submission of proposed changes

### ISSUE THREAD

**Issue by stuchalk** [Systems-Modeling/SysML-v2-Release#55]
I submitted a PR with some proposed changes to files that are part of the Quantities and Units section of v2.  I have some more proposed changes and would like to know you want them as I find them (multiple PRs) or all at once.  Happy to do what you suggest.

**Comment by seidewitz** [comment]
Thank you for your suggestions. However, the standard library models will be part of the specification artifacts to be submitted to the OMG. For IP reasons, we cannot accept any contributions to these artifacts other than from SST member organizations that have since our Teaming Agreement. 

We can review your suggestions and possibly an an issue for them to our internal development backlog. However, there is limited time to make further changes before our final submission date to OMG of February 20. After the submission of the proposed specification and its adoption by OMG as a "beta specification", there will be a formal process for the submission and consideration of issues from the public, including the necessary granting of certain IP rights.
