### ISSUE TITLE
SysML Kernerl is not connecting with JuypterLab

### ISSUE THREAD

**Issue by AntonXaver** [Systems-Modeling/SysML-v2-Release#56]
Hello together,

I installed everything according to the documentation on Windows. 
But when I want to start in JupyterLab it tries to connect to the SysML Kernel but after a few seconds it stays disconnected
![image](https://user-images.githubusercontent.com/126654265/222074845-fab904b8-5872-4ceb-8def-a4d5986e6334.png)

![image](https://user-images.githubusercontent.com/126654265/222074544-1ba9380e-0a63-46f2-a420-16c561a34183.png)

I also installed the SysML extension in JupyterLab. Not working either.

BR

**Comment by seidewitz** [comment]
There should be a log related to starting the SysML kernel in the shell in which you start Juptyer Lab. Perhaps you can se there what the problem is.

For further support for installation problems, though, it is better to post your question to the [SysML v2 Release Google Group](https://groups.google.com/g/sysml-v2-release), rather than in a GitHub issue. (If you have not already joined the group, you will need to request membership while logged into a Google account.)
