### ISSUE TITLE
The file 2C-SysML_v1_to_v2_Transformation is missing information

### ISSUE THREAD

**Issue by WintersMontagne10335** [Systems-Modeling/SysML-v2-Release#60]
Hello！Sorry to bother you.
Some content is missing because it is too long.Section C.2.2.1 is a typical but not the only part.
In addition, how to realize the conversion from SysML v1 to SysML v2? Can I use ATL?

**Comment by Weilkiti** [comment]
Hi,

Thanks for the info! We fixed the layout issues for the final submission of SysML v2. It will be available in the next release.

We have a pilot implementation of the transformation based on ATL. It is not yet public because we do not have resources for documentation and proper setup so that it can be used without a personal introduction.

Cheers,
Tim


Tim Weilkiens
(Consultant & Executive Board Member)

------------------------------------------------
oose Innovative Informatik eG
Kontorhaus Montblanc, Schulterblatt 36, D-20357 Hamburg
GnR 1067 local court Hamburg, VAT ID DE296653247
Management Board: Nicola Jährig, Felix Heppner, Tim Weilkiens
Chairman of the Supervisory Board: Dr. Michael Hofmann
Fon: +49 (40) 41 42 50-0, Fax: +49 (40) 41 42 50-50
Internet: www.oose.de E-mail: ***@***.***



From: Winters Montagne ***@***.***>
Sent: Montag, 13. März 2023 14:28
To: Systems-Modeling/SysML-v2-Release ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Systems-Modeling/SysML-v2-Release] The file 2C-SysML_v1_to_v2_Transformation is missing information (Issue #60)


Hello！Sorry to bother you.
Some content is missing because it is too long.Section C.2.2.1 is a typical but not the only part.
In addition, how to realize the conversion from SysML v1 to SysML v2? Can I use ATL?
