### ISSUE TITLE
Direction port in training example

### ISSUE THREAD

**Issue by braghieri** [Systems-Modeling/SysML-v2-Release#8]
In the SysML-v2-Release\sysml\src\training\11. Ports\Port Example.sysml , the directions of the items 
 `fuelSupply` and `fuelReturn` are always the same in ports `FuelOutPort` and `FuelInPort`.  

 Instead, in the example SysML-v2-Release\sysml\src\training\11. Ports\Port Conjugation Example.sysml, they are reversed by means of the Conjugation.

Is the first example to be  fixed ?

**Comment by seidewitz** [comment]
The example is actually presented correctly in the training material [Intro to the SysML v2 Language-Textual Notation.pdf](https://github.com/Systems-Modeling/SysML-v2-Release/blob/master/doc/Intro%20to%20the%20SysML%20v2%20Language-Textual%20Notation.pdf), but the model provided in the release is, indeed, incorrect. This will be fixed in the next release. Thank you for reporting it.

**Comment by seidewitz** [comment]
Fixed for 2021-05 release.
