### ISSUE TITLE
Seeming warnings out of the box on usage in Eclipse IDE post install

### ISSUE THREAD

**Issue by borromeotlhs** [Systems-Modeling/SysML-v2-Release#84]
The two "abstract ref connection" constraints that seek to re-define an instance of 'trailerHitch' to different multiplicities errors out with the warning: "Should be an accessible feature (use dot notation for nesting)" without any type of build or modification to source code pulled from github.  Is this normal?  I understand what this is attempting to validate, but don't see any alternative ways in either the graphical or textual notation guides to SysMLv2 pdfs provided.  Ignoring for now, obviously, but constraints and the ability to validate/verify upon performance of an action might deserve further documentation?
![Screenshot 2024-02-21 131230](https://github.com/Systems-Modeling/SysML-v2-Release/assets/1448570/b100c424-0cbc-4cf4-91e8-a13c8ca85d42)

**Comment by seidewitz** [comment]
This is a known issue. We have left the warnings in this model until we decide whether there is an underlying problem here that requires a deeper resolution.

However, looking at this again, I realized that the error annotation was misleading. The warning actually comes from the ref connections in the actions inheriting the related features from the connections to which they are bound. However, the related features of the original connections are out of context within the actions, which is what is causing the warnings. Removing the **`connection`** keywords eliminates the warnings, with the same semantic effect (as stated in the comments).

This will be revised in the next release. Thanks for your comment leading to me taking another look at this.
