### ISSUE TITLE
Warning on connection sysml example 

### ISSUE THREAD

**Issue by braghieri** [Systems-Modeling/SysML-v2-Release#9]
I am experimenting with the connection definition between parts; I wrote a couple of sysml files that are appearing equivalent to me but I have a **Warning** on the `connect` statement for one of the two files.

![image](https://user-images.githubusercontent.com/48685521/117303670-42cfed00-ae7d-11eb-8c99-58253869e513.png)

[Examples.zip](https://github.com/Systems-Modeling/SysML-v2-Release/files/6434709/Examples.zip)

**Comment by seidewitz** [comment]
Even though `a::p` and `a::b::p` look like property paths, they are actually qualified names that statically resolve (through inheritance, in this case) to the named features. In this case, the actual ownership path for these features is `A::p` and `B::p`, rooted in the part definitions `A` and `B`, respectively. Therefore the connection seems to be between a featuresof the part definition `A` and a feature of the part definition `B`, rather than the inherited features within the part `a`. The warning results because the connection itself is in yet another context ("top level" within the package), which is semantically inconsistent.

To avoid this warning, you need to provide "local" connection points within the part `a`:
```
part a : A {
    out redefines p;
    part redefines b {
        out redefines p:
    }
}
```

The qualified names `a::p` and `a::b::p` then resolve to the redefining features within the context of `a`. Since the connection usage is also at the "top level" with `a` in the package `Connections Example`, it is then legal to connect features within `a`. (It would also work to nest the connection within `a`.)

Of course, it is obviously inconvenient to have to do these redefinitions. This has been a known usability issue with the language for some time, and we have considered different possible ways to fix it, including leaving it to be handled by "tool wizards" rather than changing the language (interestingly, this turns out to be much more natural with the graphical notation than the textual notation). However, we have now decided that the best way to resolve this issue is to introduce a "dot" notation, which can be used instead of qualified names to express "feature paths" that truly record what is intended to be connected. So, once release 2021-04 is available (in the next one or two weeks), you will be able to avoid the warning by simply changing the connection usage in your example to
```
connect a.p to a.b.p;
```

(Note that questions like this, about the language itself, rather than the implementation, are better posted in the [SysML v2 Release](https://groups.google.com/g/sysml-v2-release) group, rather than on GitHub. If you would like to discuss this issue further, please re-post it to that group.)
