### ISSUE TITLE
beginner with SysML v2, and encountered an EOF error when trying to import xx in Jupyter

### ISSUE THREAD

**Issue by jkrescue** [Systems-Modeling/SysML-v2-Release#96]
`import ISQ::mass;`

ERROR:missing EOF at 'import' (14.sysml line : 1 column : 1)

**Comment by hpdekoning** [comment]
@jkrescue : As stated in the README file:

To ask questions about using this release or to provide feedback, join the SysML v2 Release Google Group.
* Go to https://groups.google.com/g/sysml-v2-release while logged into a Google account.
* Select “Apply for Membership”.
  * Please provide your full name, organizational affiliation and interest in SysML.
* Once your application has been accepted, you can post to the group using the email [sysml-v2-release@googlegroups.com](mailto:sysml-v2-release@googlegroups.com).

Quick answer:

Since release 2024-07 it is not allowed anymore to import into the global (root) namespace, and also you must provide the visibility (public, private or protected) on imports.

So typically you start a model with a `package` and use `private import`, like so:

```
package MyPackage {
    private import ISQ::mass;

    // rest of your model
}
```
